service: serverless-url-demo

custom:
   tableThroughput: 5
   stage: ${opt:stage, self:provider.stage}
   tableName: ${self:service}-${opt:stage, self:provider.stage}

provider:
   name: aws
   runtime: nodejs8.10

functions:
   main:
      handler: src/main/index.handler
      events:
         - http:
            path: /
            method: get
      memorySize: 256
      timeout: 3
   create:
      handler: src/create/index.create
      role: CreateLambdaRole
      events:
         - http:
            path: /create
            method: post
      memorySize: 256
      timeout: 3
   redirect:
      handler: src/redirect/index.redirect
      role: RedirectLambdaRole
      events:
         - http:
            path: /{slug}
            method: get
      memorySize: 256
      timeout: 3

resources:
   - ${file(./resources/dynamoDb.yml)}
   - ${file(./resources/createIamRole.yml)}
   - ${file(./resources/redirectIamRole.yml)}
